# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: Build project
on: [ pull_request, push ]

jobs:
  build:
    strategy:
      matrix:
        java: [ 16 ]
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Java ${{ matrix.java }} setup
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Make gradlew executable
        if: runner.os == 'Linux'
        run: chmod +x ./gradlew

      - name: Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '16' }} # Only upload artifacts built from LTS java on one OS
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/
