# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Publish release on repository

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        if: runner.os == 'Linux'
        run: chmod +x ./gradlew

      - name: Publish on Maven repository
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :mod:publishMavenJavaPublicationToMavenRepository
        env:
          ORG_GRADLE_PROJECT_publish_username: ${{ secrets.PUBLISH_USERNAME }}
          ORG_GRADLE_PROJECT_publish_password: ${{ secrets.PUBLISH_PASSWORD }}
